### ISSUE TITLE
failed to pod install

### ISSUE THREAD

**Issue by zl00** [lingoer/SwiftyCharms#4]
[!] Invalid `Podfile` file: [!] Unsupported options `{:exclusive=>true}` for target `SwiftyCharmsTests`..

**Comment by zhigang1992** [comment]
Are you using cocoaPods 1.0-beta ?
Just update the project, should compile now

**Comment by zhigang1992** [comment]
If it still didn't work, try removing the `Pods` folder and install again

**Comment by zl00** [comment]
Thanks a lot!
I chose pod (version:0.39.0), then can pod update.
